apiVersion: v1
kind: Namespace
metadata:
   name: lab1

---

apiVersion: v1
kind: Pod
metadata:
  name: vault-pod
  namespace: lab1
  labels:
    app: vault
spec:
  containers:
  - name: vault
    image: vault:1.13.3
    ports:
    - containerPort: 8200
      name:  http
