apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
  namespace: default
  labels:
    app: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: frontend
        image: "ifilyaninitmo/itdt-contained-frontend:master"
        env:
        - name: REACT_APP_USERNAME
          value: "Borya"
        - name: REACT_APP_COMPANY_NAME
          value: "Kvas"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: default
  labels:
    app: react
spec:
  selector:
    app: react
  ports:
  - protocol: TCP
    port: 8201
    targetPort: 3000
  type: NodePort

