apiVersion: v1
kind: Namespace
metadata:
   name: lab2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
  namespace: lab2
  labels:
    app: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: front
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
        - name: REACT_APP_USERNAME
          value: "Borya"
        - name: REACT_APP_COMPANY_NAME
          value: "Kvas"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: lab2
  labels:
    app: react
spec:
  selector:
    app: react
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 3000
  type: NodePort

