apiVersion: v1
kind: Namespace
metadata:
   name: lab3

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: secret-rs
  labels:
    app: react
    namespace: lab3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: front
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
        - name: REACT_APP_USERNAME
          valueFrom:
              configMapKeyRef:
                name: secret-cm
                key: REACT_APP_USERNAME_FROM_CM
        - name: REACT_APP_COMPANY_NAME
          value: "Kvas"
          valueFrom:
              configMapKeyRef:
                name: secret-cm
                key: REACT_APP_COMPANY_NAME_FROM_CM
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: lab3
  labels:
    app: react
spec:
  selector:
    app: react
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 3000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-cm
  namespace: lab3
  labels:
    app: react
data:
  REACT_APP_USERNAME_FROM_CM: "Borya"
  REACT_APP_COMPANY_NAME_FROM_CM: "Kvas"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-react
  namespace: lab3
spec:
  rules:
   - host: kvass.com
     http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: react-service
                port: 
                  number: 8200
