apiVersion: v1
kind: Namespace
metadata:
   name: lab3

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-cm
  namespace: lab3
  labels:
    app: react
data:
  usn: "Borya"
  cpn: "Kvas"

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: secret-rs
  namespace: lab3
  labels:
    app: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: front
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
        - name: REACT_APP_USERNAME
          valueFrom:
              configMapKeyRef:
                name: secret-cm
                key:  usn
        - name: REACT_APP_COMPANY_NAME
          valueFrom:
              configMapKeyRef:
                name: secret-cm
                key: cpn
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: lab3
  labels:
    app: react
spec:
  selector:
    app: react
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: lab3
  labels:
    app: react
spec:
  rules:
   - host: kvass.com
     http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: react-service
                port:
                  number: 8200

---

apiVersion: v1
kind: Secret
metadata:
  name: react-tls
  namespace: lab3
  labels:
    app: react
type: kubernetes.io/tls
data:
  tls.crt: |
LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUYvekNDQStlZ0F3SUJBZ0lVTHNYckdYS29TS1Q0RGN0VDVFdEZIU2xmbVRBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZNHhDekFKQmdOVkJBWVRBbEpWTVE4d0RRWURWUVFJREFaTmIzTmpiM2N4RHpBTkJnTlZCQWNNQmsxdgpjMk52ZHpFTk1Bc0dBMVVFQ2d3RVMzWmhjekVXTUJRR0ExVUVDd3dOUkhKcGJtdHBibWNnYTNaaGN6RVNNQkFHCkExVUVBd3dKYTNaaGMzTXVZMjl0TVNJd0lBWUpLb1pJaHZjTkFRa0JGaE51YVd0cGRESXlNekpBWjIxaGFXd3UKWTI5dE1CNFhEVEl6TVRBeE5ERTRNRFEwTUZvWERUSTBNVEF4TXpFNE1EUTBNRm93Z1k0eEN6QUpCZ05WQkFZVApBbEpWTVE4d0RRWURWUVFJREFaTmIzTmpiM2N4RHpBTkJnTlZCQWNNQmsxdmMyTnZkekVOTUFzR0ExVUVDZ3dFClMzWmhjekVXTUJRR0ExVUVDd3dOUkhKcGJtdHBibWNnYTNaaGN6RVNNQkFHQTFVRUF3d0phM1poYzNNdVkyOXQKTVNJd0lBWUpLb1pJaHZjTkFRa0JGaE51YVd0cGRESXlNekpBWjIxaGFXd3VZMjl0TUlJQ0lqQU5CZ2txaGtpRwo5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBa2pLcFlXdUszK2QwWEhmSW1pbWJXS3B6WDBGSllzMUczeTkxCjV3ZUZuSjdEM0lYQm9QcG9zSzFDSXVRRkM0cXFybDNvM2czU1FsYmxSV3pWWUV1MTU2OStsdmtmaXdZUE5ycFcKdVR2cDVGT090LytwL0VPOWU1cWkxYW5IRW5aWEtPNjNvRDJ4QkxKdjZlV1E2UHVWWHR1MFNkekNQbXJmWnlwZwp4clo2MVhEL2lPTkNaQWpXK3pCdDJhQ3ZkWDdhYUs1TlhMZC91TktOMXoveWV2dTRvS2FYdzQyWW5HdlNWRTZyClpsOHZCZ3U0K2Mray9qMjFUMU1QVXZsQUpmSWFLRUNnZklFdG4zbktnZlIyVVFIQXMzY29mcjJHTGU4Skc5WnAKT2YyZTRwb0YrbEpwd1hCMDdJQVhjRGxvT0cwdWZxd1B5OG5DS3Ztc3Q2STlSYko0NWM0Sm5VTG1xZmxEZzJFKwpQa3BrYmpOamlHQmdzV3RwRjhPN1lkUGppRHUvMlIvczFOeG1Waks4T2RQOU02UkJYckFYQjhLZjduOFFBRWQ3CmE5a0l2MVJXaG1xeGlpemZTWXpSaDlJRzQ5d2w2MkIyQWJralM5VXl4U2o3OERsTWh5ODgzYlAvME9MeDl0SU0KSFNadGVkVlJzNjUzbjdKVDV0WURycjIwckM2VFNpQ1M1ZGwrc0k0V0MxbW1RbldoenExYzZSOWNUdFplK3RkYwo3YS96RFNjeEMyM3Z3RnpVRkdkK20xYlVoSkJJcVRXMy9SbTZjWmlyc0pmNlNpR1pqbnBFZTZEWE1tdVVXRkdtCmZOQ1FFamRScGJwRzhKVEtTY3UvOWRNZEYxNW1YMjdpVU1LOW1UTm5DZWJVZWZWYnNqT2JJTEtSTjRVaVRXNS8KZ29sQlNSc0NBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGSjMzU0JxZktEQkw5Vm9OamxTeVJUd2ZFb2FGTUI4RwpBMVVkSXdRWU1CYUFGSjMzU0JxZktEQkw5Vm9OamxTeVJUd2ZFb2FGTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFJT1NFWktISTVxbVVCVVYwV2JGTm9RWENILzRkZkl0U1A3RTArLy8KVjJzRjcwU25LbmpULzVRRFhnVmgzZHpWQytqdkMwTkJzZktSNEVEcHFtMFZ3dHNuSzZXUUVvdFkvNWkxMUhFbAptSjR5cWpkeExIN1E0UDdsUjI5c0d3UERBbW5Jd2xEVjN6SGJwVUFucjF3dGhIRlEyQXZXZnlyMktWbjNMTExRCmdONFNsc0lBMUVtck1iMkZPTWpkcDlOTmxLR1p5cGZzTU1LSnEvZUpWMnNZdTJoNE0vdVdXaWRhRVZjRmhoTmoKQ2xYR2hqQ1hEYm94RHFIb2RhYWdsUjFPTEM0MFdhTkEyNHJZMmRHVWJHT1RjWlZxM2l2SXR0YzJZdm5oc2pqQwpSUnFGajFVSEMwVXo0a0FWU1dLK0YvYU00eGZCbmhjUFdyTWFYVENoZytJalpyMnQyaEljUG1JQm1Uc0JYVm4rClM2NENtemZDcnNDWXZtVHBpSnhSSHhIUHYrMDZlZjV0TUhzWEduczA2QkhOaGowK2szcFdMejVQRDIyYW05QkUKV0RoMHVocnJ3dnUrOWlrM3FNSmNicDNPNzVERytFV0dtRDd4Zm1GMG1XVXNpY05oOVJZZlJPNndzcnVSc1dXaAo3dUNvTGJkeEpGOVBqUEFJN09HRFl3K3orSmtiaXN4bVBnenVHL01ySzJQc0tzWi9jRERDNEZleUVuQ2tHYUFFCkN0VkM1UGZjRFpqQXRhVndBYXR5OVluWWdrTGJLTUxwNmZicVVWUUZ1RSsrOTdMMlArVUNwaXk0WGVsZ29pQnQKaDZDbjQrbk5zT0RxUUZFMy91TVZ3WWc5Q2JyRldYK3luU1Q5aHVBNnNJUzBFRnlpVEdqd21QYXp3RklIZjVEcQpnV0dDCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: |
LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1N3d2dna29BZ0VBQW9JQ0FRQ1NNcWxoYTRyZjUzUmMKZDhpYUtadFlxbk5mUVVsaXpVYmZMM1huQjRXY25zUGNoY0dnK21pd3JVSWk1QVVMaXFxdVhlamVEZEpDVnVWRgpiTlZnUzdYbnIzNlcrUitMQmc4MnVsYTVPK25rVTQ2My82bjhRNzE3bXFMVnFjY1NkbGNvN3JlZ1BiRUVzbS9wCjVaRG8rNVZlMjdSSjNNSSthdDluS21ER3RuclZjUCtJNDBKa0NOYjdNRzNab0s5MWZ0cG9yazFjdDMrNDBvM1gKUC9KNis3aWdwcGZEalppY2E5SlVUcXRtWHk4R0M3ajV6NlQrUGJWUFV3OVMrVUFsOGhvb1FLQjhnUzJmZWNxQgo5SFpSQWNDemR5aCt2WVl0N3drYjFtazUvWjdpbWdYNlVtbkJjSFRzZ0Jkd09XZzRiUzUrckEvTHljSXErYXkzCm9qMUZzbmpsemdtZFF1YXArVU9EWVQ0K1NtUnVNMk9JWUdDeGEya1h3N3RoMCtPSU83L1pIK3pVM0daV01ydzUKMC8wenBFRmVzQmNId3AvdWZ4QUFSM3RyMlFpL1ZGYUdhckdLTE45SmpOR0gwZ2JqM0NYcllIWUJ1U05MMVRMRgpLUHZ3T1V5SEx6emRzLy9RNHZIMjBnd2RKbTE1MVZHenJuZWZzbFBtMWdPdXZiU3NMcE5LSUpMbDJYNndqaFlMCldhWkNkYUhPclZ6cEgxeE8xbDc2MTF6dHIvTU5KekVMYmUvQVhOUVVaMzZiVnRTRWtFaXBOYmY5R2JweG1LdXcKbC9wS0labU9la1I3b05jeWE1UllVYVo4MEpBU04xR2x1a2J3bE1wSnk3LzEweDBYWG1aZmJ1SlF3cjJaTTJjSgo1dFI1OVZ1eU01c2dzcEUzaFNKTmJuK0NpVUZKR3dJREFRQUJBb0lDQUFpcWJmTmpSSk1rQ0dXYkNGS2dKRTNKClhDQlhQU0ZHeFQ2OHZmS1IybHRFVkhlYW5LTmZVaVRiOWZHd054WEUrekxiYk9EV1huYlR4SGxzeTQ1OFVLbFcKejFNdTRxNGVScDJWZlVjenJYTnF3eGFNMWhETlpSejJTY0o4QlFCSEZNQ0VUVXpTd2lvSGQ2VXVxbW5CaDB3bQpNSEU0cUxxVi9VaTZaMmRtekZUOFhneWt4K0NXT21pTkZ4M1JVa1VwSnZqdEVTVkkvVExCbFdwVnkvUG9xL0xkCjArODlHMU1IYWZSck5zV0lBOUtjYXlENTR4MjErb2Z1R1BQTE1XNUp6UGF3MTdKd2NPZGIrS3gxSzNaK3hDeEkKUDROUHNabmxqdEpOOUFtQ1N4bWV1Z1N5aU43MHp3RndVRVdpbHpKajVjMXJGVjZjb2dVKzBVV1AxRC9NQVZhWQpsb0l2VjFNdk5PZ3AxYUM3SDdRTjJKUk9ZNUhaU3lxZTBmYzNvdjFqTGlyYmc1TWl5aDRla1NLeGhaOVhtTjZmCkRzUWY1NjFHd1N6bnI3c3M0c1FMWlZYelZrL29vNHFha3RMNE1EazJMR1hQWTNqVjZ1T0pPbDVWemJpTjJ3OWUKM2FaTE5nWXNpalc0VDM1aU1hMkhmSDBEUlh1c29JZCtXc1lSeml6eEl2dUg1ZThOUzgzV3F3b0tLMzVKRVdkcwo3cEFYZ0NYYVdaemhaOG9pWTVuSVZiNEpSRlRiOU10VmVCTXNaUHQwL0plcHl1T3FHQ0lSckFmTHlFMWRHT1pUCmhPdm1rV3JUMnA4ak10SG56ZW5HZ3VHazFwSnQxR0trbXdtZGpwVHJBbkhGbWZUVDlrM1EvaU4xL2Vyd3laL0EKL0F3YnZjbi9PbnA0SU93QzFmdnRBb0lCQVFDLzQwS3g4TnpyZmtGd0ltb2s3cjcvcloxRDFWL3UzeUF6Zm5pZApKa2RUUTJYUW5LWWNUakx1QUE2TE5LTytjNFZlelhVTndHNitLcW94RVlWdW1kUnRxaldlRDNDU0FySjNucTVRCkQrc3VRM2ZUQ2FYSEErNVNSQ2NKbDlPWHh4ZjNnVlp3Wmx4US9yekxnQThMMkdzYVRvaE5KMVBvWkk0ejVkVDYKbGFWK2lqN1JCRjREclFtNHd6d2ZycFBtUXdxbzdBMTVBMjRoUnVXaG1Kbkc5VHVhampUeFJnYTMyTVlXbnZNVQpWMDNZdzBINzgvcE5XSVY1YkRrWm03alF3U0hvOVZqY0tWa2hES2RyRlhLNmU4VHU0a0pERzc3ZDFTTWkwcE1ICjVRVC9JR3lvWmYydFlHeHQrVXh3QlR6SWhPUytzZTdZbXovVnZvYmU0K1FnSUh5ZEFvSUJBUUREQzJrbEZ2cnYKOHdGOVJQTjE4b2tLMXJ0R1J0NmhnTitzNU8rZmVxMmxuTURaUWNPWnNNWXF5VkF0b0RBcTJwaDloZ0s3R1grVgpkME14VDVuS0RkbkhvZWR2d2VGOU9VNDl0RGJZZExPN0JSTGl3Q1YxUWxvalcrMm9iWEVCdmhwNFJYZHJZZVVJCjJOWFFKWENjM1JGQWpjNHQvd29oYU1BbHFQUHJZNXVKVGc4cUZkRjVMQnd3bVZzOTZpYlVSQitjYm9mMkc5STQKQlplTHdyWHBTQzVCdmtMTm85R2FsNXVJc29uNXltTnA0ZUFVcHBweUt5ckYrcVpnRjA5a3h1NjdMOHZGVnpjZQp6SW51cmduRzNDaW01ZHVvaGY0Q0VYWTRvcENaRGtUWnhKRXJQeUxIYnI5TTRFVFRHTnF6bDR0MGNhSzVoVjdFCk9iQ1lUTUFNelVNWEFvSUJBQ1NDNDQva0dzVWNVdXM1UVNVaDRHblo2UkNkS3hIU2x0ZjFlcEc4Vk5uOCt3U0UKcWY2OHltZ0t6cm1pSEg0Q2tTQUd5L3ovM3BLRW43bVNjZWNua2dvRDF3dnFPQ3N3SkRFcW1sUlZreFJNZGlKTAp0YVYybEFSSFAzNU55MDhYN1BHRlJLTkNkdEphaGlYYWlnSmcvWkFWM1UyQTdEQk40ZGp5SkdKQjB5bU91SUVnCjZacWRkRG9adS9qelNPVUpZSi9mdW5pS05JeFVaeUVtWGl4RFFVSVpTTzJYdTNPRDViMHNKV2g3YkM2UWlKK2UKUHNRMDBjRFczTTZJbU5Qdnk3bjk1UmlQTFl4aVVnRElKZnBoem9qOXVFbjRuNHFxSVhOZ3llVTRxSWk2N0xIbQpKaXkxS2l5S3dRYVhtSWMyOGlkdXg5bWpRTFEwK29peXFCZU0xdWtDZ2dFQkFLeHFFTmRObWlPMGo3TjUyVEdCClpXMWtab1g0TGVOY2RkMXpQdk9lVVpRZG5rZ3ZIMFprQXJsZDNmZUhMQzBsc1RqODFyc29EaVZGR091bEx4QnkKNy9uT0FEVkZrUnZPSllEY0pzTnZYbFhMWldkMmJXWmJjaXpoblpPT3N4L1VPYmZweUdmdlVMUmlZWmV2RVA1SgpXVy9VS3RkMEpUTmxVcjIzdlc5dVROYXlYeXRYd0NVNlBlMGtFNGtHeks1RlRpQk5nUGlvblVzU2ZtVjRpTEFnCk0ydkFVWE5SQmY5L1Yya2VVbU95YWZEMlQ4eFJmaVBBVHY1VjFPOEtqQTlNMzBvdk5SVk1SSmlBUE1uMXBRVGEKSjBGcDNhUDZWcERqZUxzVjBYYkxLMGZKd0g0WFFKcEZKdXhCTC9YZmVhemFJTmVkZ0RnNVVvMXBaZGNydVhWWAptWjhDZ2dFQWQ2QUloeHphdEx2VjRubGZHc2gyTisyTjgyK3g0WDJ3OVhnS1hoSVNxRmNaNHVTcVlGNXhrNXRuCk9CZWxRM25qN1U2ak5DclgrRm9JZ3NHbG85VGJtVm5GTzFFYThJd1h4TWlTNzFHWTgvTHFMRUpzZEdaV3BIbHIKZ2NMS1VJZXE0Ykgwa20vOVlCNUxxZC9HRUhnYUVTeW9OdlljTUtxNWp0V1VUT0s4YVNCSUwzVDJQemJwZ2ZNOApCdnBtcmVGSzZLaG8xcEJhbm5FYkxQTENiTlRCbHpscTBNWGJwd2R1cElhNUM3UUF3TlA2Q0U3aUVOMm4rR3BJCjRRWUFUYXRvQWZpTkIxUzBwN0pRRnBqQWVFNGVCOXdDRUVYUWhvMm9KQXBZckM2ak5RbDVuUWVxMEtYOUVoTW0KeW1vSlFidVc4RUJQbW0xU3FyZlRUUit5c2grR0NBPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
